name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile: [rails_7_1, rails_7_2, rails_8_0]
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
      - run: bundle install --jobs 4
      - run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
      - run: bundle install --jobs 4
      - run: bundle exec rubocop

  release:
    needs: [rspec, rubocop]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
      - run: bundle install --jobs 4
      - name: Build and push gem to RubyGems
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          sed -i "s/0.0.0/${GITHUB_REF_NAME}/g" lib/nexus_semantic_logger/version.rb
          gem build nexus_semantic_logger.gemspec
          gem push nexus_semantic_logger-*.gem